### ISSUE TITLE
Tracking quality indicator

### ISSUE THREAD

**Issue by dzhoshkun** [dzhoshkun/wherepy#1]
Simple tracking quality indicator similar to a [wi-fi indicator](https://www.google.co.uk/search?q=wifi+indicator&client=ubuntu&hs=ea0&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjHoarGw6zZAhXsIMAKHeWgAHgQ_AUICigB&biw=1513&bih=740)

States:
* [ ] no device
* [ ] no data
* [ ] weak signal => one "bar"
* [ ] okay signal => two "bars"
* [ ] strong signal => three "bars"

**Comment by dzhoshkun** [comment]
* [ ] depends on #7

**Comment by dzhoshkun** [comment]
* [ ] something along these lines:

```
Signal strength: |>>>>>>>>  | 85 %
Error:           |<<        |
```
