### ISSUE TITLE
Support for saving tracking data

### ISSUE THREAD

**Issue by dzhoshkun** [dzhoshkun/wherepy#2]
* [x] PyYAML dependency
   * [x] README
   * [x] `setup.py`
* [x] Each launch should create a session file  `000000-2018-02-17-08-49-13.yml` within root sessions folder => will be addressed part of the application
* [x] `SessionLog` class:
   * [x] `SessionLog(filepath)`:
   * [x] `append(tool_pose)`:
     1. [x] `tool_pose` => YAML representation
     1. [x] save the pose:

```yaml
wherepy:
  version: git-described
0:
  port1:
    quaternion: "q0 q1 q2 q3"
    coordinates: "x y z"
    error: e
    quality: qu
    timestamp: t0
1:
  port1:
    quaternion: "q0 q1 q2 q3"
    coordinates: "x y z"
    error: e
    quality: qu
    timestamp: t1
[...]
N:
  port1:
    quaternion: "q0 q1 q2 q3"
    coordinates: "x y z"
    error: e
    quality: qu
    timestamp: tN
```

**Comment by dzhoshkun** [comment]
* [ ] the following diff for tests:

```diff
diff --git a/tests/io/test_session_log.py b/tests/io/test_session_log.py
index c5bccc6..a3e55bc 100644
--- a/tests/io/test_session_log.py
+++ b/tests/io/test_session_log.py
@@ -1,17 +1,29 @@
 import unittest
+from os.path import (join, isfile)
+from uuid import uuid4
 from wherepy.io import SessionLog
 
 
 class SessionLogTestCase(unittest.TestCase):
 
+    @staticmethod
+    def unique_string(length=6):
+        return uuid4().hex[:length].upper()
+
     def test_invalid_filepath_raises(self):
-        self.__fail()
+        invalid_filepath = join('this', 'should-not', 'exist', 'session.yml')
+        with self.assertRaises(OSError):
+            SessionLog(filepath=invalid_filepath)
 
     def test_session_file_created(self):
-        self.__fail()
+        filepath = 'session-{}.yml'.format(SessionLogTestCase.unique_string())
+        SessionLog(filepath=filepath)
+        self.assertTrue(isfile(filepath))
 
     def test_tool_pose_appended_to_session_file(self):
-        self.__fail()
-
-    def __fail(self):
-        self.fail('not implemented')
+        filepath = 'session-{}.yml'.format(SessionLogTestCase.unique_string())
+        session_log = SessionLog(filepath=filepath)
+        for tool_pose in SessionLogTestCase.tool_poses:
+            session_log.append(tool_pose)
+        for i, tool_pose in enumerate(SessionLogTestCase.tool_poses):
+            self.assertTrue(i == tool_pose)  # validate all

```
