### ISSUE TITLE
CLI tracking quality indicator

### ISSUE THREAD

**Issue by dzhoshkun** [dzhoshkun/wherepy#24]
Something along these lines:

```
Signal: |>>>>>>>>  |    85 %
Error:  |<<        | 1.35 mm
```

Edge cases:
* [x] infinite tracking error

```
Signal: |        |    0 %
Error:  |<<<<<<<<|  infinity
```

```python
print(u"\u221E")
```

* [x] no device connected

```
Signal: |NO CONNECTION|   0 %
Error:  |NO CONNECTION|
```

* [x] https://github.com/dzhoshkun/wherepy/issues/1#issue-297989305

**Comment by dzhoshkun** [comment]
Related to #1

**Comment by dzhoshkun** [comment]
* [ ] `wherepy-indicator` CLI app

**Comment by dzhoshkun** [comment]
```
| Device [tick or cross] | Connection [tick or cross] | Quality: [======>   ]  69 %  | 
```

**Comment by dzhoshkun** [comment]
The following patch for testing indicator:

```diff
diff --git a/wherepy/app/_indicator.py b/wherepy/app/_indicator.py
index 4fdca23..295a1d9 100644
--- a/wherepy/app/_indicator.py
+++ b/wherepy/app/_indicator.py
@@ -63,6 +63,32 @@ def display_status(connected, quality=None, error=None, msg=None):
     stdout.flush()
 
 
+if __name__ == '__main__':
+    from random import (random, randrange, uniform)
+
+    nouns = ("puppy", "car", "rabbit", "girl", "monkey")
+    verbs = ("runs", "hits", "jumps", "drives", "barfs")
+    adv = ("crazily.", "dutifully.", "foolishly.", "merrily.", "occasionally.")
+    adj = ("adorable", "clueless", "dirty", "odd", "stupid")
+
+    while True:
+        sleep(1)
+        quality = random()
+        error = uniform(1, 4)
+        msg = None
+        if quality > 0.55:
+            connected = True
+        else:
+            connected = False
+        if error > 1.9:
+            error = float('inf')
+            quality = 0
+        else:
+            num = randrange(0, 5)
+            msg = nouns[num] + ' ' + verbs[num] + ' ' + adv[num] + ' ' + adj[num]
+        display_status(connected, quality, error, msg)
+
+
 def run_indicator_cli(tracker, update_rate=10):
     """Run live CLI quality indicator of passed tracker at desired
     update rate.

```

**Comment by dzhoshkun** [comment]
* [ ] document in usage

**Comment by dzhoshkun** [comment]
* [ ] test live
