### ISSUE TITLE
Tracker and ToolPose classes

### ISSUE THREAD

**Issue by dzhoshkun** [dzhoshkun/wherepy#3]
The following higher-level classes for representing a tracker connection and tool poses should be implemented:

* [x] abstract `Tracker` class:
    * [x] `connect()` raising `IOError` (auto-`connect()` on `__init__`)
    * [x] `disconnect()` raising `IOError`
    * [x] `connected()`
    * [x] `tool_pose = capture(tool_id)` raising
        - [x] `IOError` if not `connected()`
        - [x] `ValueError` if `tool_id` invalid
* [x] `ToolPose` class:
    * [x] `id()` => not `None`
    * [x] `quaternion()` => of `len()` 4
    * [x] `coordinates()` => of `len()` 3
    * [x] `quality, error = quality()` => between 0.00 - 1.00 (100%), error is what is returned by tracking system
    * [x] `timestamp()` => `python -c "import time; print('{:.10f}'.format(time.time()))"`
       - [x] default is `now()`

This is related to #2

**Comment by dzhoshkun** [comment]
* [ ] remove deactivation of `too-few-public-methods`
