### ISSUE TITLE
Pip installable hierarchy

### ISSUE THREAD

**Issue by dzhoshkun** [dzhoshkun/wherepy#4]
1. [x] document installation via GitHub repo
1. [x] `tests` (?) => #14 
1. [x] `setup.py`
    1. [x] dependencies: `pyndicapi`
1. [x] `setup.cfg`  (only Python 2 ) => using `python_requires` instead
1. [x] `wherepy-collector-gui [--session-folder /path/to/session/folder]` command
1. [x] `wherepy-collector-cli [--session-folder /path/to/session/folder]` command (?)
1. [x] create a `wherepy.home*( = '$HOME/.wherepy/'` folder #10 
1. [x] create a `wherepy.sessions_default() = os.path.join(wherepy.home(), 'sessions')` folder #10 
1. [x] default session folder: `os.path.join(wherepy.sessions_default, '2018-02-17-09-17-14-serial-no')` #11  
1. [x] `wherepy.io` package #2 
1. [x] `wherepy.track`package  #3 
1. [x] `wherepy.gui` package #1 
1. [x] `wherepy.app` package with `Collector` class
    1. [x] `Collector(graphical=True)` (?)
